# Generated by Django 4.2.8 on 2024-04-06 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 12, 25, 46, 953006, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
