# Generated by Django 5.0.1 on 2024-04-03 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 19, 16, 12, 955601, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
