# Generated by Django 4.2.8 on 2024-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('question', models.CharField(max_length=80)),
                ('answer', models.CharField(max_length=80)),
            ],
        ),
    ]
